### ISSUE TITLE
zencode_exec_tobuf crash in swift

### ISSUE THREAD

**Issue by digital-worx-dev** [dyne/Zenroom#109]
zencode_exec_tobuf don't working in swift - ios app.  Crashed...

Tried with following code:
//        let outputSize: size_t = 1024 * 128
//        let errorSize: size_t = 1024 * 128

//        let z_output = UnsafePointer<Int8>(Int8(malloc(outputSize * MemoryLayout<Int8>.size)))
//        let z_output = UnsafeMutableRawPointer(malloc(outputSize * MemoryLayout<Int8>.size)).assumingMemoryBound(to: Int8.self)
//        let z_error = UnsafeMutableRawPointer(malloc(outputSize * MemoryLayout<Int8>.size)).assumingMemoryBound(to: Int8.self)

        
//        let z_output = stringToUnsafeMutablePointer(message: ""+malloc(outputSize * MemoryLayout<Int8>.size))
        
//        let z_output = UnsafeMutablePointer<Int8>.allocate(capacity: outputSize * MemoryLayout<Int8>.size)
//        let z_error = UnsafeMutablePointer<Int8>.allocate(capacity: errorSize * MemoryLayout<Int8>.size)
//
//        zencode_exec_tobuf(stringToUnsafeMutablePointer(message: text), stringToUnsafeMutablePointer(message: ""), stringToUnsafeMutablePointer(message: ""), stringToUnsafeMutablePointer(message: ""), 1, z_output, outputSize, z_error, errorSize)

zenroom_exec working but I want to get the JSON Response from the static Lib. 
zenroom-ios.a and zenroom.h attached.
[zenroom_a_h.zip](https://github.com/DECODEproject/Zenroom/files/4598501/zenroom_a_h.zip)
 
used function:
   func stringToUnsafeMutablePointer(message: String) -> UnsafeMutablePointer<Int8> {
        var messageCString = message.utf8CString
        return messageCString.withUnsafeMutableBytes { mesUMRBP in
            return mesUMRBP.baseAddress!.bindMemory(to: Int8.self, capacity: mesUMRBP.count)
        }
        
    }

**Comment by andrea-dintino** [comment]
You were using an outdated version of zenroom.h showing an older version of the functions signatures. We since updated the documentation accordingly and linked the latest zenroom.h from the download page.
