### ISSUE TITLE
Figuring out current release version

### ISSUE THREAD

**Issue by zzappie** [dyne/Zenroom#117]
Hello dear zenroomers!

I'm trying to make sense of release tags.
The VERSION file states 1.0.0
Python package is 1.0.12
The latest tag in git is 1.0.5 while latest github release is 0.8.1
Javascript is 1.1.1

Are these "bindings" folders different packages or not? Or they all
refer to the same thing? I'm asking because there is no clear distinction.

And the last question is -- can I assume that I should be able to build 
zenroom bindings from the latest commit on the master branch?

**Comment by puria** [comment]
Hey, the bindings have a different release management from Zenroom itself, so the versions are not the same. It is a good idea maybe to have some signature to call to see which version of Zenroom they are using (thanks for the hint I'll implement it).

You can build all the bindings straight from `main` (aka master), and if something does not work please raise your hand ;)
Ciao.

**Comment by zzappie** [comment]
Tanks for clarification!
I was confused because the go bindings Makefile for example uses the
latest git tag.

Tests for python binding are not passing for me at this point of time.
I'll dublecheck whether I messed up something and report back how it
went.

**Comment by puria** [comment]
closing this issue, figure out that the best way in any binding language is to run straight and ask zenroom itself ;) by executing the following zenroom script:

`print(VERSION.original)`
