### ISSUE TITLE
Issue with credentials printed out in Url64

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#134]
With the script: 

`
Rule output encoding url64

Rule input encoding url64

Scenario credential: read and validate the credentials 

Scenario petition: create the petition 

Given that I am known as 'Alice' 

Given I have my valid 'credential keypair' 

Given I have my valid 'credentials' 

Given I have a valid 'verifier' inside 'MadHatter' 

When I aggregate the verifiers 

When I create the credential proof 

When I create the petition 'More privacy for all!' 

Then print the 'uid' as 'string' inside 'petition' 

Then print 'uid' as 'string'

Then print data

`

Keys: 

`
{
	"Alice": {
		"credential_keypair": {
			"public": "BE8ERC16Xsdg3PaGDwLYgEoagKWC1Eb-88aXg09qhvTv_onrHigAR5bbtFMcyWF9_xOeiY9Xvrt1lcdpWmwbKc_FThYOKj8ezwPlkZ5a75karo-d762W5EzuXw-76gI7_w",
			"private": "StbYmlCs7YlIm3UmSpBoEwgdFRFaJuB2j4H10p7wRYY"
		},
		"credentials": {
			"h": "BDokjEscxc9dE3MpPVFTKJ-WD1VRx3rcvHOyAlsQifwoukL9hQI1y9qfALfcS1_DqiCCvSg15FFev8kSW1yC-NxTuxCM5urU-PV5BeLQEKJSROntjYZfcBbm4kru7XI7UQ",
			"s": "BCXBxSbzILQoWYCBIeMYxt2-MKdLEqDIF-SmmzyXpEx6AMMutSn3PhPxBYEMfixVuQJuTe93FNfbgYFVL5RGVEZsSoLGB53zw3pWmWWOgCkPQy3D4ikjoQv3TQv_UEqmnQ"
		}
	},
	"MadHatter": {
		"verifier": {
			"alpha": "Ax9PWJpMePSumkm7L4n1bNaFMazOkGUNvkZe_kWXe0ZZdkkjQYd4vE6LEOW1QvVdNzb8QWFINrgaWp3e-9Qci4Ay7x0HdHxwwqGld-bLUNME1wVLBtWAAZSsAcAWAfQESYeLaDCAm9qjRV_ngYSo6L_EIRhoJExRhJfsoiA40UGksnmHdwJnih_v25SHTQ-EK7cIDyjAa6dhxUrOzNzKguR6lC2Wjf2HHpkYBFW6FEHmka-hB700X6dWA8lsrO37",
			"beta": "D0VgCzzAFJlVwbqJYNvKvoa18CWyoNBK0136o495PR91FItBdlrd81S9GG7_KxwOMsJKPJUeGOlnGH6aZ_OuIprHCWd5ij5vXhb0BDxGlN2g2FfO6c7bC_FVEPW0_8n1DJS00TwG_9a6No5-ZSrheQm24K-FeRBnJE6Hm8-Qd8wMWb6Ea-pMxc8dYecUeQA8PbESZgFBqJ2pWoBghhumDYlVBVAxA-UNeOb3-WcMIImSr93059aQUJADKzs2VywQ"
		}
	}
}
`

When executing, the first two chars of the credential keypair and the credentials, come out wrong: 

 "credential_keypair": {
    "private": "StbYmlCs7YlIm3UmSpBoEwgdFRFaJuB2j4H10p7wRYY",
    "public": "**A0**8ERC16Xsdg3PaGDwLYgEoagKWC1Eb-88aXg09qhvTv_onrHigAR5bbtFMcyWF9_w"
  }

And 

 "credentials": {
    "h": "**Az**okjEscxc9dE3MpPVFTKJ-WD1VRx3rcvHOyAlsQifwoukL9hQI1y9qfALfcS1_Dqg",
    "s": "**Ay**XBxSbzILQoWYCBIeMYxt2-MKdLEqDIF-SmmzyXpEx6AMMutSn3PhPxBYEMfixVuQ"
  }

**Comment by jaromil** [comment]
This JSON has been created by an older version of Zenroom adopting a different curve than the `BLS383`. Therefore the public key of the credential keypair gets mapped to a different point on a different curve and changes radically its value. As we release Zenroom 1.2 long-term-support then all data structures used must be created by a 1.x-LTS version.
