### ISSUE TITLE
Delete all empty and null objects from a dictionary

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#175]
I need to be able to import a large dictionary which is a template, where most values are empty or null, and print out only those that are not empty/null

Suggestion a Zencode statement like: 

`When I delete all the empty objects from 'myStringDictionary'`

This statement should cycle all the content of the dictionary (and subdictionaries) and delete every object that has an empty value or a 0.

In alternative, a Zencode like: 

`Then I print the 'myStringDictionary' without the empty objects`

**Comment by jaromil** [comment]
ACK! best is in `when` since that is the read/write HEAP space.

Ambiguity between `empty string` and `zero` should be solved.

I propose 2 implementations:
1. `When I delete all zero values in ''`
2. `When I delete all empty strings in ''`
