### ISSUE TITLE
String dictionary with empty string

### ISSUE THREAD

**Issue by pasfranc** [dyne/Zenroom#177]
```
Scenario 'ecdh': create keypair from data

# Loading the user name from data
Given my name is in a 'string' named 'username'

# Loading the answers from 3 secret questions. The user will have to pick the 3 challenges from a list 
# and have to remember the questions - the order is not important cause Zenroom will sort alphabetically 
# the data in input
#
# NOTE: the challenges will never be communicated to the server or to anybody else!
Given I have a 'string dictionary' named 'userChallenges'

# Loading the pbkdf received from the server, containing a signed hash of known data
Given that I have a 'string' named 'key_derivation'  

# Loading the individual challenges, in order to have them hashed 
# and the hashes OPTIONALLY stored by the server, to improve regeneration of the keypair
Given I have a 'string' named 'whereMyParentsMet' in 'userChallenges'
Given I have a 'string' named 'myFirstPet' in 'userChallenges'
Given I have a 'string' named 'myHomeTown' in 'userChallenges'
Given I have a 'string' named 'nameOfFirstTeacher' in 'userChallenges'
Given I have a 'string' named 'surnameOfMotherBeforeWedding' in 'userChallenges'


# Hashing the user's challenges and renaming it
When I create the hash of 'userChallenges'
and I rename the 'hash' to 'userChallenges.hash'

# appending the user challenges' hash to the pbkdf, hashing the result and renaming it 
When I append 'userChallenges.hash' to 'key_derivation'
When I create the hash of 'key_derivation'
and I rename the 'hash' to 'concatenatedHashes'

# Creating the keypair from the hash just created
When I create the keypair with secret key 'concatenatedHashes'

When I create the 'base64 dictionary'
and I rename the 'base64 dictionary' to 'hashedAnswers'


# Creating the hashes of the single challenges, to OPTIONALLY help 
# regeneration of the keypair

When I create the hash of 'whereMyParentsMet'
and I rename the 'hash' to 'whereMyParentsMet.hash'
When I insert 'whereMyParentsMet.hash' in 'hashedAnswers'

When I create the hash of 'myFirstPet'
and I rename the 'hash' to 'myFirstPet.hash'
When I insert 'myFirstPet.hash' in 'hashedAnswers'

When I create the hash of 'myHomeTown'
and I rename the 'hash' to 'myHomeTown.hash'
When I insert 'myHomeTown.hash' in 'hashedAnswers'

When I create the hash of 'nameOfFirstTeacher'
and I rename the 'hash' to 'nameOfFirstTeacher.hash'
When I insert 'nameOfFirstTeacher.hash' in 'hashedAnswers'

When I create the hash of 'surnameOfMotherBeforeWedding'
and I rename the 'hash' to 'surnameOfMotherBeforeWedding.hash'
When I insert 'surnameOfMotherBeforeWedding.hash' in 'hashedAnswers'



Then print my 'keypair'

# Comment the line below, if you don't want to output the hashes of the challenges
Then print 'hashedAnswers'
```

Keys

```
{
	"userChallenges": {
		"whereMyParentsMet": "Roma",
		"myFirstPet": "ScoobyDoo",
		"myHomeTown": "Amsterdam",
		"nameOfFirstTeacher": "",
		"surnameOfMotherBeforeWedding": "null"
	},
	"username": "xxx",
	"key_derivation": "qf3skXnPGFMrE28UJS7S8hdT8g=="
}
```

Result

Logs:
System memory manager in use
MUTT print functions in use
ECDH curve is SECP256K1
Memory in use: 305 KB
[W] Zencode is missing version check, please add: rule check version N.N.N[!] from_string: invalid string size: 0
[!] operation aborted
[W] Given I have a 'string dictionary' named 'userChallenges' 2[W] Scenario 'ecdh'[W] . Given my name is in a 'string' named 'username'[W] . Given I have a 'string dictionary' named 'userChallenges'[W] . [31;1m[!][0m /zenroom_common.lua:109: operation aborted[W] {
a_GIVEN_in = {
KEYS = {
key_derivation = "qf3skXnPGFMrE28UJS7S8hdT8g==",
userChallenges = {
myFirstPet = "ScoobyDoo",
myHomeTown = "Amsterdam",
nameOfFirstTeacher = "",
surnameOfMotherBeforeWedding = "null",
whereMyParentsMet = "Roma"
},
username = "xxx"
}
},
b_WHEN_ack = {},
c_THEN_out = {}
}[!] Zencode execution error
[!] Script:
ZEN:begin()
ZEN:parse([[
Scenario 'ecdh': create keypair from data
# Loading the user name from data
Given my name is in a 'string' named 'username'
# Loading the answers from 3 secret questions. The user will have to pick the 3 challenges from a list
# and have to remember the questions - the order is not important cause Zenroom will sort alphabetically
# the data in input
#
# NOTE: the challenges will never be communicated to the server or to anybody else!
Given I have a 'string dictionary' named 'userChallenges'
# Loading the pbkdf received from the server, containing a signed hash of known data
Given that I have a 'string' named 'key_derivation'
# Loading the individual challenges, in order to have them hashed
# and the hashes OPTIONALLY stored by the server, to improve regeneration of the keypair
Given I have a 'string' named 'whereMyParentsMet' in 'userChallenges'
Given I have a 'string' named 'myFirstPet' in 'userChallenges'
Given I have a 'string' named 'myHomeTown' in 'userChallenges'
Given I have a 'string' named 'nameOfFirstTeacher' in 'userChallenges'
Given I have a 'string' named 'surnameOfMotherBeforeWedding' in 'userChallenges'
# Hashing the user's challenges and renaming it
When I create the hash of 'userChallenges'
and I rename the 'hash' to 'userChallenges.hash'
# appending the user challenges' hash to the pbkdf, hashing the result and renaming it
When I append 'userChallenges.hash' to 'key_derivation'
When I create the hash of 'key_derivation'
and I rename the 'hash' to 'concatenatedHashes'
# Creating the keypair from the hash just created
When I create the keypair with secret key 'concatenatedHashes'
When I create the 'base64 dictionary'
and I rename the 'base64 dictionary' to 'hashedAnswers'
# Creating the hashes of the single challenges, to OPTIONALLY help
# regeneration of the keypair
When I create the hash of 'whereMyParentsMet'
and I rename the 'hash' to 'whereMyParentsMet.hash'
When I insert 'whereMyParentsMet.hash' in 'hashedAnswers'
When I create the hash of 'myFirstPet'
and I rename the 'hash' to 'myFirstPet.hash'
When I insert 'myFirstPet.hash' in 'hashedAnswers'
When I create the hash of 'myHomeTown'
and I rename the 'hash' to 'myHomeTown.hash'
When I insert 'myHomeTown.hash' in 'hashedAnswers'
When I create the hash of 'nameOfFirstTeacher'
and I rename the 'hash' to 'nameOfFirstTeacher.hash'
When I insert 'nameOfFirstTeacher.hash' in 'hashedAnswers'
When I create the hash of 'surnameOfMotherBeforeWedding'
and I rename the 'hash' to 'surnameOfMotherBeforeWedding.hash'
When I insert 'surnameOfMotherBeforeWedding.hash' in 'hashedAnswers'
Then print my 'keypair'
# Comment the line below, if you don't want to output the hashes of the challenges
Then print 'hashedAnswers'
]])
ZEN:run()
[!] /zencode.lua:294: Given I have a 'string dictionary' named 'userChallenges'
[!] Error detected. Execution aborted.
[*] Zenroom teardown.
Memory used: 352 KB

**Comment by andrea-dintino** [comment]
This was fixed with the latest commit: an object with an empty valued is not loaded by Zenroom, but now the error message is more clear.
