### ISSUE TITLE
Object encoding conversion

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#182]
I need a statement like: 

`When I convert 'myHexObject' to 'base64'`

**Comment by jaromil** [comment]
@andrea-dintino the output conversion belongs to 'Then' as this is write-only and not changing the internal data.

`Then I print '' (from '') as '' (in '')

**Comment by andrea-dintino** [comment]
I know that... but I would need an extra script just for the conversion - quite impractical

**Comment by jaromil** [comment]
OK

`When I convert the encoding of 'object name' to 'encoding name'`

this can operate on the ZEN.CODEC

**Comment by jaromil** [comment]
Solved by

Then print as

Eventually useful for internal members of dictionaries, but use cases have not arisen yet.
