### ISSUE TITLE
Loading a dictionary with empty or null object

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#190]
When loading

```
{
	"myData": {
		"myString1": "",
		"myString2": null,
		"myString3": "Hello World!"
	}
}
```

Using: 

```
Given I have a 'string dictionary' named 'myData'
Then print data
```

The expected result would that Zenroom loads "myData", containing only "myString3". Stops instead with the errors: 

_[W] Given I have a 'string dictionary' named 'myData'[W] . [31;1m[!][0m /zenroom_common.lua:128: operation aborted[W]_ 

_[!] /zencode.lua:364: Given I have a 'string dictionary' named 'myData'_

**Comment by jaromil** [comment]
done in e781a261b626494043b43f7ba9ed018e7bb7d59a

new statement:
```
When I create a pruned dictionary of ''
```
