### ISSUE TITLE
Statement that copies object from dictionary

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#196]
Using this data:

```
{
   "dataTime0":{
      "Active_energy_imported_kWh":4027.66,
      "Ask_Price":0.1,
      "Currency":"EUR",
      "Expiry":3600,
      "Timestamp":1422779638,
      "TimeServer":"http://showcase.api.linx.twenty57.net/UnixTime/tounix?date=now"
   },
   "nested":{
      "dataTime1":{
         "Active_energy_imported_kWh":4030,
         "Ask_Price":0.15,
         "Currency":"EUR",
         "Expiry":3600,
         "Timestamp":1422779633,
         "TimeServer":"http://showcase.api.linx.twenty57.net/UnixTime/tounix?date=now"
      },
      "dataTime2":{
         "Active_energy_imported_kWh":4040.25,
         "Ask_Price":0.15,
         "Currency":"EUR",
         "Expiry":3600,
         "Timestamp":1422779634,
         "TimeServer":"http://showcase.api.linx.twenty57.net/UnixTime/tounix?date=now"
      }
   }
}
```

I need a zencode like this:

`When I create a copy of 'Timestamp' in 'dataTime0'`
`When I create a copy of 'Currency' in 'dataTime1' in 'nested'`

Which should create the objects 'Timestamp' and 'Currency' at **root level**.

**Comment by jaromil** [comment]
@andrea-dintino ACK. Need to keep consistent order from left to right:
```
When I create a copy of 'Currency' in 'nested' in 'dataTime1'
```

**Comment by andrea-dintino** [comment]
Update:

I need a zencode like this:

`When I create the copy of  element 'Timestamp' in 'dataTime0'`
`When I create the copy of  element 'Currency' in 'nested' in 'dataTime1' `

Which should create the objects 'Timestamp' and 'Currency' at **root level**. 

At the same, the copy dictionary statement should be changed to: 

`When I create the copy of  dictionary 'dataTime1' in 'nested'`

**Comment by jaromil** [comment]
Without changing the current code of Zencode, I could run this test succesfully on the data you provide:
```
Given I have a 'string dictionary' named 'nested'
When I create the copy of 'dataTime1' from dictionary 'nested'
and I rename 'copy' to 'dataTime1'
and I create the copy of 'Currency' from dictionary 'dataTime1'
Then print the 'copy'
```
Let's discuss off-list if this needs some improvements or is fine as-is.

**Comment by andrea-dintino** [comment]
Yes! Ideally we'd also need a statement like: 

`When I create the copy of 'Ask_Price' from dictionary 'dataTime0' from dictionary 'nested' `
