### ISSUE TITLE
Crates.io upload

### ISSUE THREAD

**Issue by puria** [dyne/Zenroom#217]
🎊 for the Rust bindings ;)
Would be nice to have (guess also for testing purposes) some sort of Continuous Deployment uploaded to crates.io something in fashion of:

https://github.com/dyne/Zenroom/blob/master/.github/workflows/javascript.yml#L42-L68
or
https://github.com/dyne/Zenroom/blob/master/.github/workflows/python.yml#L75-L87

that each commit on main after the rust test goes ✅ creates a pre-release...

@jaromil @jpopesculian how do you see that?

**Comment by jaromil** [comment]
Right now we have the test in github actions https://github.com/dyne/Zenroom/blob/master/.github/workflows/rust.yml

Cargo works by importing zenroom directly from github

Not sure about best strategy and if anything else is needed for a versioned upload?

**Comment by puria** [comment]
closing this ;)
