### ISSUE TITLE
Zenroom no longer builds for different ecdh curves

### ISSUE THREAD

**Issue by adam-burns** [dyne/Zenroom#264]
The `build/config.mk` change:
`ecdh_curve := ED25519`
followed by `make linux`

or builds using the meson build method:
```
meson build bb -Decdh_curve=ED25519
ninja -C bb
```
now return the error

`zen_ecdh.c:64:10: fatal error: ecp_SECP256K1.h: No such file or directory
`

**Comment by jaromil** [comment]
@adam-burns thanks, yes it is a known issue, let this ticket also be a reminder about builds with different ecdh curves
