### ISSUE TITLE
`zencode_exec` exiting without error/output in Rust bindings

### ISSUE THREAD

**Issue by jpopesculian** [dyne/Zenroom#266]
# Description

When using the Rust bindings, `zencode_exec` seems to exit with an exit code of 0 without throwing an errors or giving any output apart from the debug output.

* Version: `13bf777`
* Target: `x86_64-unknown-linux-gnu`
* Rust version: `1.56.1` (`59eed8a2a` 2021-11-01 stable)

# Example

```rust
use std::process::exit;
use zenroom::{zencode_exec, ZenError};

fn main() {
    let script = r#"
    Given nothing
    Then print the string 'approve'
    "#;
    let config = "";
    let keys = "";
    let data = "";
    match zencode_exec(script.into(), config.into(), keys.into(), data.into()) {
        Ok(res) => {
            println!("{}", res.output);
            exit(0);
        }
        Err(ZenError::Execution(res)) => {
            eprintln!("{}", res.logs);
            exit(1);
        }
        Err(ZenError::InvalidInput(err)) => {
            eprintln!("{}", err);
            exit(2);
        }
    }
}
```
```toml
[package]
name = "zenroom-minimal-example"
version = "0.1.0"
edition = "2021"

[dependencies]
zenroom = { git = "https://github.com/dyne/Zenroom" }
```
# What happens

The code exits with an exit code of 0 with the following output

```
 .  Release version: 2.0.0
 .  ECDH curve is SECP256K1
 .  ECP curve is BLS381
 .  Memory in use: 473 KB
```

# Expected to happen

The code should exit with an exit code of 0 and this output

```
 .  Release version: 2.0.0
 .  ECDH curve is SECP256K1
 .  ECP curve is BLS381
 .  Memory in use: 414 KB
{"output":["approve"]}

```

# Additional details

I can confirm that the zenroom version `134f5ae` is working

**Comment by jaromil** [comment]
@jpopesculian es! some things recently changed in the execution (also in the direction to have a parser call as you suggested previously) and the exit code may have been affected. I'm on this, your rust example helps troubleshooting, easier than with py or js, thanks!
