### ISSUE TITLE
Error printing all data after verify keypair

### ISSUE THREAD

**Issue by pasfranc** [dyne/Zenroom#277]
The script:
`Scenario 'ecdh': create keypair from data

Given my name is in a 'string' named 'email'
Given I have a 'string dictionary' named 'userChallenges'
Given that I have a 'string' named 'key_derivation'

Given I have a 'string' named 'question1' in 'userChallenges'
Given I have a 'string' named 'question2' in 'userChallenges'
Given I have a 'string' named 'question3' in 'userChallenges'
Given I have a 'string' named 'question4' in 'userChallenges'
Given I have a 'string' named 'question5' in 'userChallenges'

When I create the hash of 'userChallenges'
and I rename the 'hash' to 'userChallenges.hash'

When I append 'userChallenges.hash' to 'key_derivation'
When I create the hash of 'key_derivation'
and I rename the 'hash' to 'concatenatedHashes'

When I create the keypair with secret key 'concatenatedHashes'

When I create the 'base64 dictionary'
and I rename the 'base64 dictionary' to 'hashedAnswers'

When I create the hash of 'question1'
and I rename the 'hash' to 'question1.hash'
When I insert 'question1.hash' in 'hashedAnswers'

When I create the hash of 'question2'
and I rename the 'hash' to 'question2.hash'
When I insert 'question2.hash' in 'hashedAnswers'

When I create the hash of 'question3'
and I rename the 'hash' to 'question3.hash'
When I insert 'question3.hash' in 'hashedAnswers'

When I create the hash of 'question4'
and I rename the 'hash' to 'question4.hash'
When I insert 'question4.hash' in 'hashedAnswers'

When I create the hash of 'question5'
and I rename the 'hash' to 'question5.hash'
When I insert 'question5.hash' in 'hashedAnswers'

Then print all data`

with the input:

`{
  "data": {
  "email": "john@doe.com",
  "hashedAnswers": {
    "question1.hash": "c4kZLBh0JP7qLZ6SctCbbAwtxCJ0DCf1UqP7lBxjCxE=",
    "question2.hash": "2hauYmg/8TGnG5IeCTzlFKHvw1XpxbKaMdmEUbUNQ2c=",
    "question3.hash": "ABPAH+DQlCCbi9PSO4+W26vNAd3SoDnuuoLRiRrPDWE=",
    "question4.hash": "fIPY5zX5Yh8Y3xXyaosWSsNiGoPLigqrm06azAxY+FA=",
    "question5.hash": "daJd/6yRxfPtiQU+WgM6fbP6hreZi2NeksbkOy02aXo="
  },
  "john@doe.com": {
    "previousKeypair": {
      "private_key": "CQ/DFp3LHDKQg6rXTmyzsrKXaLcbqHp/hE1ePIpqQqU=",
      "public_key": "BApwkHluY9Z9x7a3LSAZ9Oq4/JuUhEzX65ag6yeKpH2huT1xuSaXGKMk/pF0PDDeiBIaado3flnHivYaFOyMlLU="
    }
  },
  "key_derivation": "o4fzjrBsh3Nh3i4HoPeYh72xNQ==��\u0018�N\u0018:SPo;#�\u001d� �)=�!���;�6�ԥ",
  "userChallenges": {
      "question1":"Parigi",
      "question2":"ScoobyDoo",
      "question3":"Amsterdam",
      "question4":"Mrs Doubtfire",
      "question5":"Gervasoni"
    }
},
  "keys": {}
}`

Returns the error:

`Release version: 2.0.0\n .  Build commit hash: bc3e6e39\n .  ECDH curve is SECP256K1\n .  ECP curve is BLS381\n .  Memory in use: 341 KB\n[W] Zencode is missing version check, please add: rule check version N.N.N[W] Then print all data\t2[W] nil[W]  .  Scenario 'ecdh'[W]  D  ZEN:pick found email[W]  D  ZEN:pick found userChallenges[W]  D  ZEN:pick found key_derivation[W]  D  ZEN:pickin found question1 in userChallenges[W]  D  ZEN:pickin found question2 in userChallenges[W]  D  ZEN:pickin found question3 in userChallenges[W]  D  ZEN:pickin found question4 in userChallenges[W]  D  ZEN:pickin found question5 in userChallenges[W]  .  \u001b[31;1m[!]\u001b[0m **/zencode_then.lua:215: attempt to index a nil value (field '?')[W]** {\n    a_GIVEN_in = {},\n    b_WHEN_ack = {\n        concatenatedHashes = octet[32] 7993dc8d6eb86243abde7dfbbcbe8ee3d97b1bbfeb34e0c26cc881933c70ae33,\n        hashedAnswers = {\n            [\"question1.hash\"] = octet[32] 7389192c187424feea2d9e9272d09b6c0c2dc422740c27f552a3fb941c630b11,\n            [\"question2.hash\"] = octet[32] da16ae62683ff131a71b921e093ce514a1efc355e9c5b29a31d98451b50d4367,\n            [\"question3.hash\"] = octet[32] 0013c01fe0d094209b8bd3d23b8f96dbabcd01ddd2a039eeba82d1891acf0d61,\n            [\"question4.hash\"] = octet[32] 7c83d8e735f9621f18df15f26a8b164ac3621a83cb8a0aab9b4e9acc0c58f850,\n            [\"question5.hash\"] = octet[32] 75a25dffac91c5f3ed89053e5a033a7db3fa86b7998b635e92c6e43b2d36697a\n        },\n        key_derivation = octet[114] 6f34667a6a72427368334e68336934486f506559683732784e513d3defbfbdefbfbd18efbfbd4e183a53506f3b23efbfbd1defbfbd20efbfbd293defbfbd21efbfbdefbfbdefbfbd3befbfbd36efbfbdd4a57ffbe9a018ee4e183a53506f3b23cc1df820da293d8521f9f8853bb836a5d4a5,\n        keypair = {\n            private_key = octet[32] 7993dc8d6eb86243abde7dfbbcbe8ee3d97b1bbfeb34e0c26cc881933c70ae33,\n            public_key = octet[65] 043145f039349179b6ca8eb0c94c0cbd501c1283534157a92c59baac133fbbab39118a8294ab1750bae840043e8e588dfdc71d1ad7c023f6f674f56c2f7e87a3a7\n        },\n        question1 = octet[6] 506172696769,\n        question2 = octet[9] 53636f6f6279446f6f,\n        question3 = octet[9] 416d7374657264616d,\n        question4 = octet[13] 4d727320446f75627466697265,\n        question5 = octet[9] 4765727661736f6e69,\n        userChallenges = {\n            question1 = octet[6] 506172696769,\n            question2 = octet[9] 53636f6f6279446f6f,\n            question3 = octet[9] 416d7374657264616d,\n            question4 = octet[13] 4d727320446f75627466697265,\n            question5 = octet[9] 4765727661736f6e69\n        },\n        [\"userChallenges.hash\"] = octet[32] 7ffbe9a018ee4e183a53506f3b23cc1df820da293d8521f9f8853bb836a5d4a5\n    },\n    c_THEN_out = {\n        concatenatedHashes = \"eZPcjW64YkOr3n37vL6O49l7G7/rNODCbMiBkzxwrjM=\"\n    }\n}\u001b[1;31m[!]\u001b[0m Zencode execution error\n\u001b[1;31m[!]\u001b[0m /zencode.lua:624: Then print all data\n\u001b[1;31m[!]\u001b[0m Error detected. Execution aborted.\n\u001b[1;32m[*]\u001b[0m Zenroom teardown.\n .  Memory used: 437 KB\n`

The error seems to be in the "then" phase: **/zencode_then.lua:215: attempt to index a nil value (field '?')[W]**
This is not happening in zenroom 2.2.1

**Comment by puria** [comment]
Ciao @pasfranc,
thanks for reporting seems that happens just on the 2.2.2 of the js binding, correct?
Seems that is fine with the @next tag
I'll make a release soon then

**Comment by jaromil** [comment]
I confirm latest zenroom version works, recent fixes to CODEC applied.

**Comment by puria** [comment]
Just release 2.2.3, and it's fixed with 💖
