### ISSUE TITLE
Input encoding not found: string_dictionary

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#284]
The restroom script: 

```
Rule caller restroom-mw
Given that I have an endpoint named 'endpoint1'
Given that I have an endpoint named 'endpoint2'
Given I have a 'string dictionary' named 'myData'
Given I connect to 'endpoint1' and save the output into 'myData'
Then print 'myData'
Then pass the output to 'endpoint2'
```

```
{
	"endpoint1": "http://showcase.api.linx.twenty57.net/UnixTime/tounix?date=now",
	"endpoint2": "https://dyneorg.free.beeceptor.com"
}
```

Produces the error:

1641908255879I[ZENROOM EXECUTION ERROR FOR CONTRACT dyneorg/1641908255559]
1641908255879Iundefined
1641908255879I Release version: 2.0.0
1641908255879I Build commit hash: b18ac4bc
1641908255879I ECDH curve is SECP256K1
1641908255879I ECP curve is BLS381
1641908255879I Memory in use: 345 KB
1641908255879I Rule caller restroom-mw
1641908255879W[W] Zencode pattern ignored: Given that I have an endpoint named 'endpoint1' 1
1641908255879W[W] Zencode pattern ignored: Given that I have an endpoint named 'endpoint2' 1
1641908255879W[W] Zencode pattern ignored: Given I connect to 'endpoint1' and save the output into 'myData' 1
1641908255879W[W] Zencode pattern ignored: Then pass the output to 'endpoint2' 1
1641908255879W[W] Zencode is missing version check, please add: rule check version N.N.N
1641908255879W[W] Given I have a 'string dictionary' named 'myData' 2
1641908255879W[W] nil
**1641908255879W[W] [31;1m[!][0m /zencode_data.lua:133: Input encoding not found: string_dictionary**
1641908255879W[W] {
1641908255879I a_GIVEN_in = {
1641908255879I myData = "1641908255"
1641908255879I },
1641908255879I b_GIVEN_in = {
1641908255879I endpoint1 = "http://showcase.api.linx.twenty57.net/UnixTime/tounix?date=now",
1641908255879I endpoint2 = "https://dyneorg.free.beeceptor.com"
1641908255879I },
1641908255879I c_WHEN_ack = {},
1641908255879I d_THEN_out = {}
1641908255879I}
1641908255879E[!] ERROR:
**1641908255879E[!] EXEC: /zencode.lua:622: Given I have a 'string dictionary' named 'myData'**
1641908255879E[!] Execution aborted
1641908255879E[!] Error detected. Execution aborted.
1641908255879S[*] Zenroom teardown.
1641908255879I Memory used: 363 KB

**Comment by jaromil** [comment]
I have no idea why you get this error (older zenroom version?) the one I get is more informative:
```
[!] ERROR:
[!] EXEC: [string "zencode"]:622: Given I have a 'string dictionary' named 'myData'
[!] Execution aborted
```
which is actually correct since 'myData' is not present in input.
```
Given I connect to 'endpoint1' and save the output into 'myData'
```
This is a restroom statement that I imagine should add 'myData' to the input BEFORE processing it with Zenroom.
Is this happening?

**Comment by andrea-dintino** [comment]
I went through this again, found the issue. Restroom passes to Zenroom this:

**Comment by jaromil** [comment]
Good idea! next commit improves checks in guess_conversion() which is used by all Given statements, it also improves error line reporting to point to the zencode statement, i.e:
```
[!] [string "zencode_given"]:273: Cannot take object: expected 'string_dictionary' but found 'string' (not a table)
[!] ERROR:
[!] EXEC: [string "zencode"]:623: Given I have a 'string dictionary' named 'myData'
[!] Execution aborted
```
