### ISSUE TITLE
Rounding bug with math 

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#295]
The script:

```
Given I have a 'number' named 'luaTime1'
Given I have a 'number' named 'luaTime2'
Given I have a 'number' named 'luaTime3'
Given I have a 'number' named '3'

When I create the result of 'luaTime1' + 'luaTime2'
And I rename the 'result' to 'res.sum1'
When I create the result of 'res.sum1' + 'luaTime3'
And I rename the 'result' to 'sum'
When I create the result of 'sum' / '3'
And I rename the 'result' to 'average'

Then print the 'average'

```
With the data:

```
{
	"3": 3,
	"luaTime1": 123123456,
	"luaTime2": 123123511,
	"luaTime3": 123123367
}

```

Will produce the result: 

```
{
  "average": 123123400
}
```

**The 'average' will always end with 00**: changing randomly the last two digits of LuaTima1, LuaTima2, LuaTima3, always produces an 'average' ending with 00

**Comment by jaromil** [comment]
floating point solution in tarantool: https://www.tarantool.io/ru/doc/latest/reference/reference_lua/decimal/

alternatively we can build our own based on BIG integers

**Comment by jaromil** [comment]
done so building our own number handling now
