### ISSUE TITLE
String manipulation for W3C-DID

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#382]
W3C-DID ids come in the format: 

`"id": "did:example:123456789abcdefghi#keys-1"`

We'd need a clever way to be able to: 
- extract the "123456789abcdefghi"
- extract the "#keys-1"

possibly creating a geneirc parsers that searches for the ":" and "#" separators, or creating statements ad-hoc for this kind of formatting.

One way to extract the "123456789abcdefghi#keys-1" is using the statement: 

`When I split the leftmost '12' bytes of 'id'
`
But I have not been able to do further manipulation as the length of the two parts of the string are variable, it could be "did:example:123#public-key-0" or even "did:example:123?service=agent&relativeRef=/credentials#degree"

**Comment by jaromil** [comment]
@andrea-dintino a mechanism leveraging strtok() would do.

When I create the array by splitting 'id' at ':'
will return an array of three elements and picking the second will return 123456789abcdefghi#keys-1

repeating the same operation on this splitting at '#' will return keys-1

**Comment by jaromil** [comment]
is this solved? @matteo-cristino

**Comment by matteo-cristino** [comment]
Yes, it was solved in 60ad600242024111d4666b5f3eb430a6e154ee52
