### ISSUE TITLE
cast zenroom.float to octet()

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#453]
implement an `:octet()` method also on floats, returning a unique octet representation of the float.

This is relevant to leverage 1st class citizenship principle and also to grant comparison of all zenroom types (see #451

**Comment by albertolerda** [comment]
It does exist https://github.com/dyne/Zenroom/blob/a84a3efdf19555b722bdc9718232e5caad05fc0f/src/zen_float.c#L305
