### ISSUE TITLE
make win-debug fails because of pq

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#480]
**make win-debug** 
(requires installing mingw-w64)

Output:
In file included from sntrup761/kem.c:5:
/home/bario/Desktop/zenroom/src/randombytes.h:9:10: fatal error: sys/syscall.h: No such file or directory
    9 | #include <sys/syscall.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: sntrup761/kem.o] Error 1
make[1]: Leaving directory '/home/bario/Desktop/zenroom/lib/pqclean'
make: *** [Makefile:165: quantum-proof] Error 2

**Comment by matteo-cristino** [comment]
Fixed by #520
