### ISSUE TITLE
GA refactoring

### ISSUE THREAD

**Issue by puria** [dyne/Zenroom#484]
Does not make sense to wait 2h long for testing and building on each commit and install zsh more than 30 times... Let's fix this workflow ;)

- [x] Research on the trend for organizing the github actions workflow
- [x] Engage reusable workflows at organization level https://github.com/dyne/workflows/
- [ ] Also make reusable steps as per [this](https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/)
- [x] Make a fast execution testing by providing PR labels [see](https://stackoverflow.com/questions/65329513/disable-github-action-workflow-only-run-when-desired)
- [x] Then we deliver a light and nice Developer eXperince ;)

**Comment by matteo-cristino** [comment]
A first idea to speed up the workflows may be to use [caching](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows).

**Comment by puria** [comment]
Bravo!

![Bravo](https://media.giphy.com/media/Rh5k1GXp0vp224lWQ9/giphy.gif)

**Comment by matteo-cristino** [comment]
Build wheels on Ubutnu and Macos inside [Build and upload nightly to PyPI](https://github.com/dyne/Zenroom/blob/master/.github/workflows/python.yml) can be made less time consuming using parallel computation by expand the matrix strategy. 
I have made the following [github action test](https://github.com/matteo-cristino/Zenroom/blob/ga/pypi_impr/.github/workflows/pypi_test.yml) with the same settings of the original github action (same python versions and same platforms), but the time consumption has dropped from more than 2 hours to [less than 25 minutes](https://github.com/matteo-cristino/Zenroom/actions/runs/3067704357/jobs/4954278082). Still no cache is used here, maybe the time can be reduced even more!!!

**Comment by puria** [comment]
> Build wheels on Ubutnu and Macos inside [Build and upload nightly to PyPI](https://github.com/dyne/Zenroom/blob/master/.github/workflows/python.yml) can be made less time consuming using parallel computation by expand the matrix strategy. I have made the following [github action test](https://github.com/matteo-cristino/Zenroom/blob/ga/pypi_impr/.github/workflows/pypi_test.yml) with the same settings of the original github action (same python versions and same platforms), but the time consumption has dropped from more than 2 hours to [less than 25 minutes](https://github.com/matteo-cristino/Zenroom/actions/runs/3067704357/jobs/4954278082). Still no cache is used here, maybe the time can be reduced even more!!!

This is awesome... @albertolerda would you also check the list of all supported platforms, maybe in the last two years they added the arch we are missing for the native python builds, in that case we can proudly say: `two pigeons with one fava bean`

**Comment by jaromil** [comment]
https://github.com/dyne/Zenroom/pull/486 just made this to speed up my side of things, the `-ccache-` makefile targets all switch using ccache when installed, plus the `meson` github actions now adopt the target `meson-ccache` with a significant speed increase when building

**Comment by jaromil** [comment]
![Screenshot_20220920-210648-770](https://user-images.githubusercontent.com/148059/191343505-a10aed74-e6bb-47c8-8932-6825d396629f.png)
with ccache now all meson builds and tests take less than 3m 😎

**Comment by puria** [comment]
To skip the CI in PR commits (not to run them per each time) there is a default behaviour described here https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

**Comment by jaromil** [comment]
can we mark this as resolved?
