### ISSUE TITLE
Zencode line to check match within a list of strings/hashes

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#49]
Zencode should be present get the value of an arbitrary key in the incoming data and then return error if that key is not contained inside a list of valid values. This can also imply hashing of values to avoid privacy-sensitive storage of lists.

(From usecase of credential-api in decidim, formulated with @Andrea-Tabbles)

**Comment by puria** [comment]
@jaromil 💓

**Comment by jaromil** [comment]
:heart_decoration:

**Comment by jaromil** [comment]
Implemented quite some time ago:
```
the '' is not found in ''
the '' is found in ''
the '' is found in '' at least '' times
```
