### ISSUE TITLE
Print base64 to number returns nothing

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#527]
Code:

```
Given I have a 'base64' named 'b64'
Then print the 'b64' as 'number' 

```
Data:

```
{
	"b64": "CTlQid3NvdizBrYjqIwNLIrHGeFccqHzlQ/jsYovLJA="
}

```
Output:

[]

1669105655528I Release version: 3.0.0
1669105655528I Build commit hash: b10867b
1669105655528I Memory manager: mimalloc
1669105655528I ECDH curve is SECP256K1
1669105655528I ECP curve is BLS381
1669105655528W[W] Zencode is missing version check, please add: rule check version N.N.N
1669105655528S[*] Script successfully executed
1669105655528I Zenroom execution completed.
1669105655528S[*] Zenroom teardown.
1669105655528I Memory used: 432 KB
1669105655528S[*] Executed in 21 ms

**Comment by jaromil** [comment]
@andrea-dintino there are two options here: report error for this conversion or, IMO preferrable, cast the data into a BIG integer and eventually report an error if too long for that
