### ISSUE TITLE
Offline RawTX signing for Planetmint

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#530]
Right now [Planetmint](https://planetmint.io) token transactions are made using Restroom and JS libraries.

We need to implement the Zencode for signing a RawTX **offline** inside Zenroom.

The crypto needed is EDDSA used in a non-standard way with sha3-256 : `eddsa_sign(sha2-512(sha3-256(transaction)))`

The UTXO encoding requres ASN.1 in particular DER and NAT

![image](https://user-images.githubusercontent.com/148059/203748506-4f0f8296-6773-44ba-bac7-2bd070761e30.png)

UTXO parsing, fund limit checking and RawTX preparation before signature can be done by the host application, sending the JSON ready for signature to Zenroom and receiving back the signed JSON.

Reference code in JS is found in the [bigchaindb js driver](https://github.com/bigchaindb/js-bigchaindb-driver/blob/17d3a02cb31749aa008061f6f49042059b775512/src/transaction.js#L218-L236)

Currently the extended Zencode implemented in Restroom looks like this:
`Then I create the signed planetmint transaction of 'planetmint_transaction'`

**Comment by matteo-cristino** [comment]
done [here](https://github.com/dyne/Zenroom/blob/master/src/lua/zencode_planetmint.lua)? Should we close this one?

**Comment by jaromil** [comment]
yes!
