### ISSUE TITLE
Given to extract data besides a string prefix or suffix

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#542]
A few use cases contemplate the presence of a string prefix or suffix besides encoded data (base64 or so) for instance in case of a `did:docu` prefix or multibase prefixed value.

A statement that allows importing data in Given besides the verified presence of a prefix or suffix would solve a lot of these use-cases

`Given I have a 'base58' named 'did token' with string prefix 'did:elohim:'`

Will extract the base58 octet following the `did:elohim` string in the `did token` input or report error if not a base58 or prefix incorrect

This can also be used to extract multibase and multihash values

**Comment by matteo-cristino** [comment]
Done in #561
