### ISSUE TITLE
move elements from dictionaries to arrays

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#544]
When running the following zencode
```gherkin
Given I have a 'string dictionary' named 'dict'
When I create the 'string array' named 'result'
When I move 'test' from 'dict' to 'result'
Then print the 'result'
```

with input
```json
{
	"dict": {
		"test": "test"
	}
}
```

The result should be 
```json
{
   "result": [
      "test"
   ]
}
```
Instead it is
```json
{
   "result": {
      "test": "test"
   }
}
```

**Comment by jaromil** [comment]
Should make sure the CODEC zentypes have 'array' or 'dictionary' correctly set and then it should be observed on `copy` or `move` actions to decide when to discard the dictionary key
