### ISSUE TITLE
fix: improve eddsa to use zenroom hash functions and portable randombytes

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#559]
Complete the integration of EDDSA to use:
- [zenroom internal sha512 hash](https://github.com/dyne/Zenroom/blob/master/lib/ed25519-donna/ed25519-hash-custom.h) (and eventually make it easy to switch hash)
- [zenroom internal randombytes](https://github.com/dyne/Zenroom/blob/master/lib/ed25519-donna/ed25519-randombytes-custom.h)

**Comment by albertolerda** [comment]
Randoms are only used inside tests and batch verification that we currently don't use in zenroom.
