### ISSUE TITLE
Name import from another variable

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#590]
Using the script
```gherkin
Given my name is in a 'string' named 'controller'
Given I have my 'keyring'
Then print the 'keyring'
```
with data
```json
{
	"controller": "Mario Bianchi",
	"Mario Bianchi": {
		"keyring": {
			"eddsa": "91BiBHt9Mu8B2svjJVsaN4VMbz919x9TEN9fAjcm5D9t"
		}
	}
}
```
results in the following error:
```
1674668437222W[W] [!] /zencode_given.lua:413: Cannot find 'Mario Bianchi'
1674668437222E[!] ERROR:
1674668437222E[!] EXEC: /zencode.lua:762: and I have my 'keyring'
```

**Comment by jaromil** [comment]
Maybe related to space/underscore ambiguity?

**Comment by matteo-cristino** [comment]
Yes, the imported name comes with a space thus it search for an object called `Mario Bianchi` while the object actual name is `Mario_Bianchi`

**Comment by jaromil** [comment]
@matteo-cristino then the fix should be to always add an underscore in place of space to all imported names (WHOAMI)
