### ISSUE TITLE
Missing verify prefix in some IfWhen statements

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#593]
The following list contains all **IfWhen** statements that are missing the **verify** prefix. 

`zencode_when`:
* '' is found
* '' is not found
* '' is found in ''
* '' is not found in ''

`zencode_verify`:
* number '' is less than ''
* number '' is less or equal than ''
* number '' is more than ''
* number '' is more or equal than ''
* the elements in '' are equal
* the elements in '' are not equal

`zencode_array`:
* the '' is not found in ''
* the '' is found in ''
* the '' is found in '' at least '' times

`zencode_petition`:
* the petition signature is not a duplicate
* the petition signature is just one more

Should we add the **verify** prefix to all these statements?

**Comment by jaromil** [comment]
@matteo-cristino I am very much in favor of this correction, because it helps to build a semantic system for zencode in future
