### ISSUE TITLE
Is CBOR format still available?

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#596]
Running the following script
```gherkin
Rule output format cbor
Scenario 'ecdh': Create the key

Given nothing
When I create the ecdh key
Then print the 'keyring'
```
Then I get the following error:
```
1675765268736E[!] ERROR:
1675765268736E[!] PARSE: /zencode_data.lua:377: attempt to index a nil value (global 'CBOR')
1675765268736E[!] Execution aborted
1675765268736E[!] Execution aborted with errors.
```
Does Zenroom still support input and output CBOR format? If it is not supported anymore then both the [get_format function](https://github.com/dyne/Zenroom/blob/master/src/lua/zencode_data.lua#L372-L382) and the [documentation](https://dev.zenroom.org/#/pages/zencode-rules) should be updated.

**Comment by jaromil** [comment]
@matteo-cristino no, the CBOR implementation we had was not passing codec tests and was removed (or should be removed where found leftovers)
