### ISSUE TITLE
Remove `zsh` as a build dependency

### ISSUE THREAD

**Issue by puria** [dyne/Zenroom#598]
Very low priority.

But on a bare new linux machine `make linux` requires `zsh`, that maybe we want to avoid, to get closer to our 0-dependency philosophy ;)

**Comment by srfsh** [comment]
Tell me if you need help with POSIX-compliant shell scripts.

**Comment by jaromil** [comment]
build/embed-lualibs is the shell script requiring it, where I use some word separator modifiers that are idiomatic to zsh

**Comment by jaromil** [comment]
I think only this modifier needs fixing:

![image](https://github.com/dyne/Zenroom/assets/148059/dc148d4f-5d85-4b83-b99e-4a5bf849cc6d)

**Comment by puria** [comment]
https://chat.openai.com/share/cd9ba8cd-dff9-45ad-a89e-12fb9356a898

**Comment by srfsh** [comment]
> Thnks @srfsh review the code below... could be a good starting point ;)
> 
> https://chat.openai.com/share/cd9ba8cd-dff9-45ad-a89e-12fb9356a898

I can certainly work on this now, now that I'm more available in general.  The first thing I can point out that is wrong in this script is that, posix doesn't have arrays, and this script is outright wrong.  :/
