### ISSUE TITLE
Foreach loop invalid transition

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#601]
Using the following script
```gherkin
Given I have a 'string array' named 'to_be_hashed'

When I create the 'base64 array' named 'array of hashes'

Foreach 'element_to_be_hashed' in 'to_be_hashed'
When I create the hash of 'element_to_be_hashed'
and I move 'hash' in 'array of hashes'
EndForeach

Then print 'array of hashes'
```
with input
```json
{
	"to_be_hashed": [
		"a",
		"b",
		"john",
		12345,
		"john@doe.com",
		"(!)"
	]
}
```
the following error is reported
```
[!] ERROR:
[!] PARSE: /zencode.lua:566: and I move 'hash' in 'array of hashes'
Invalid transition from: whenforeach
[!] Execution aborted
[!] Execution aborted with errors.
```

**Comment by albertolerda** [comment]
I would not add an `and` inside if and foreach, since it would make the state machine much more complex https://github.com/dyne/Zenroom/blob/acbca3c056d7d2809ab1244960241377ef04a0b0/src/lua/zencode.lua#L267-L297 .
We would have to add a state for each level of nesting (`andif`, `andforeach`, ...)

**Comment by jaromil** [comment]
@albertolerda this is fine, we keep the and where it already is, but not inside if and foreach blocks.

**Comment by matteo-cristino** [comment]
Inside if branches they work. They can not be used only inside foreach blocks and if blocks nested in foreach blocks

**Comment by jaromil** [comment]
solved and covered in add.bats test
