### ISSUE TITLE
copy of element from array

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#603]
Using the script 
```gherkin
Given I have a 'string array' named 'array'

When I create the length of 'array'
and I create the copy of element 'length' in array 'array'

Then print the data
```
with data
```json
{
	"array": [
		"pippo",
		"topolino",
		"pluto"
	]
}
```
the following error is reported
```
[W] and I create the copy of element 'length' in array 'array'
[W] Argument is not a position number: length
[W] [!] Argument is not a position number: length
[!] ERROR:
[!] EXEC: /zencode.lua:762: and I create the copy of element 'length' in array 'array'
[!] Execution aborted
[!] Execution aborted with errors.
```
Is this intentional? Or should we change line 130 in the following code
https://github.com/dyne/Zenroom/blob/acbca3c056d7d2809ab1244960241377ef04a0b0/src/lua/zencode_array.lua#L127-L131
to `local num = tonumber(have(pos) or pos)`

**Comment by albertolerda** [comment]
Yes, we can change it. We usually give priority to variables instead of immediate values.

**Comment by jaromil** [comment]
have(pos) is an imperative statement that blocks execution when false, the check needs to be done by hand to follow up into an `or` that supports immediate values.

There may be other similar statements needing this fix.

Also usage in this case suggests the creation of new statements for comfort and readability:
```
when I create the copy of last element in array ''
when I create the copy of last element in dictionary ''
when I create the copy of last element in ''
```
which may operate both on a array or dictionary.

**Comment by albertolerda** [comment]
I would not implement `when I create the copy of last element in dictionary ''` because, in general, dictionaries are not ordered (even though when zenroom outputs them it uses its own order).

On the other hand `when I create the copy of last element in ''` could work with both arrays and strings.

**Comment by jaromil** [comment]
@albertolerda good point! the zencode statement should perform the internal sorting function (sorted_pairs iterator) before establishing last, to be consistent with deterministic output sorting
