### ISSUE TITLE
Easy copy and rename an element inside an array or dictionary

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#606]
Faster extraction by copying an element inside a table using the `from` particle in Zencode

Example:
```
 When I create the 'signer_sda' from '3' in 'array'
```
array's keys are always numbers, or for dictionary (autodetected)
```
When I create the 'signer_sda' from 'signer' in 'addressbook'
```
autodetection made based on luatype of key and CODEC.zentype

**Comment by matteo-cristino** [comment]
Done in #624
