### ISSUE TITLE
Easy verify length of array is less or equal

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#607]
Simplify check in many statements in which we need to check that an array is less or equal
```
and I create the length of 'array'
and number 'length' is less or equal than '2'
```

This is used in secure checks for instance splitting over `_` underscore to see if a did:domain has an `_A` for admin flag

**Comment by jaromil** [comment]
```
When I verify the length of '' is less or equal "
When I verify the size of '' is less or equal "
```

length and size equivalence?

**Comment by matteo-cristino** [comment]
Done in #624
