### ISSUE TITLE
Secure strtok in C

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#608]
Substitute the `strtok` used in Lua with an implementation in C that leverages the LIBC's strtok and creates a lua table.

The strtok function is involved in some security checks and should be solid rather than based on a Lua's regexp.

**Comment by albertolerda** [comment]
Currently, we usually make `strtok` split even empty strings (e.g. splitting "a,,b" with respect to "," returns the list ["a", "", "b"].
On the other hand, `strtok` from C returns ["a", "b"], so I don't think we can use it directly.

We need something like this https://stackoverflow.com/a/26552052
