### ISSUE TITLE
Binary XOR

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#622]
Inspired by https://www.cs.ru.nl/~jhh/pub/secsem/engberg2004zeroknowledge-rfid-clean.pdf 

Zencode: 

```
Given I have a 'hex' named 'RSK'
Given I have a 'base64' named 'SSK'
Given I have a 'number' named 'bits'

When I create the XOR of 'RSK' and 'SSK'

Then print the 'XOR' as 'hex'
```

Data:

```
{
	"RSK": "3b74f1d373787b63382e75f7990de873",
	"SSK": "SQmZSTCZga9UqhPB+W0gFw==",
	"bits": 8
}

```

Output:

`{"XOR": "727d689a43e1facc6c8466366060c864"}`

**Comment by jaromil** [comment]
@andrea-dintino Zencode is not made to expose math primitives, but only a functional flow of crypto schemes.

XOR is already available in Lua and the functional flow for ZK credentials is already outlined in Zencode.

If we decide to implement another ZK crypto model, then we should make sure that it can follow the same functional flow and then name implementations as coconut and engberg to be selected from Zencode.
