### ISSUE TITLE
Refactor zencoee dictionary and array common functions in zencode_table.lua

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#629]
Since some statements present in `zencode_dictionary.zen` and `zencode_array.zen` accept both arrays and dictionaries as input it can be a good idea to group them in a different file in order to make the code easier to read and understand. Two ideas are:
* A new file `zencode_table.lua` (using the lua terminology)
* Move all of them in `zencode_when.lua` (some doubts on this option since it will enlarge a lot the file)

**Comment by jaromil** [comment]
aiming at this in #727

**Comment by jaromil** [comment]
@matteo-cristino no problem, I'm doing pretty much the same without even looking at this branch, we are well aligned

**Comment by matteo-cristino** [comment]
At the end this was not include in #727, right? I can continue it on the branch i linked previously if necessary

**Comment by jaromil** [comment]
Yes, pardon the confusion, I ended up working more on other aspects so this is not done yet. You are welcome to go forward if you want.
