### ISSUE TITLE
Add deterministic ECDSA (RFC6979)

### ISSUE THREAD

**Issue by pedro-nonfree** [dyne/Zenroom#632]
In today's event of interfacerproject.dyne.org I discovered that the implementation of ECDSA in zenroom uses the random number that makes it non deterministic

You can test it in https://apiroom.net/ with the example *Sign objects using asymmetric cryptography (ECDSA)*

Being non deterministic makes it less useful, but also more harmful in terms of security, because you need to provide enough entropy in the device for the appropriate random number generation

Using the same random number over different ECDSA signatures makes the ECDSA signatures deterministic in zenroom, but that is not cryptographically safe; because it could let to guessing and exposing the private key as it happened in several incidents

https://dev.zenroom.org/#/pages/zenroom-config?id=syntax-and-values-rngseedhex64-bytes-in-hex-notation

> This issue can be prevented by an unpredictable generation of k, e.g., a deterministic procedure as described by [RFC 6979](https://www.rfc-editor.org/rfc/rfc6979).

https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm#Security

Why is still ECDSA interesting? Because through the signature you can recover the public key, which can reduce the number of bytes to be sent (when bytes' efficiency matters).

> The choice of using Schnorr signatures over using ECDSA is not so cut and dried
> (...)
> But ultimately the benefits of using Schnorr signatures outweigh the tradeoffs, and future optimizations may resolve the inefficiencies pointed out in the quote above.

https://wiki.polkadot.network/docs/learn-cryptography#why-was-ed25519-selected-over-secp256k1 

Using RFC6979 ECDSA signatures would facilitate migration from [ethers.js](https://github.com/ethers-io/ethers.js/) (which uses [noble-secp256k1](https://github.com/paulmillr/noble-secp256k1) ) or web3 (which uses [ethereumjs-monorepo](https://github.com/ethereumjs/ethereumjs-monorepo), which uses [js-ethereum-cryptography](https://github.com/ethereum/js-ethereum-cryptography) which uses [noble-secp256k1](https://github.com/paulmillr/noble-secp256k1) since version 2). It might also facilitate that libraries considering to change crypto backend to use zenroom.

Here you have other reasons and at the end, how they did this change in go-ethereum https://github.com/ethereum/go-ethereum/issues/2190

**Comment by jaromil** [comment]
@pedro-nonfree Hi Pedro, thanks for this exhaustive explanation!

**Comment by paulmillr** [comment]
>Using RFC6979 ECDSA signatures would facilitate migration from [ethers.js](https://github.com/ethers-io/ethers.js/) (which uses [noble-secp256k1](https://github.com/paulmillr/noble-secp256k1) ) or web3 (which uses [ethereumjs-monorepo](https://github.com/ethereumjs/ethereumjs-monorepo), which uses [js-ethereum-cryptography](https://github.com/ethereum/js-ethereum-cryptography) which uses [noble-secp256k1](https://github.com/paulmillr/noble-secp256k1) since version 2). It might also facilitate that libraries considering to change crypto backend to use zenroom.

noble-secp256k1 has basically always been using deterministic ECDSA. @pedro-nonfree what do you mean by "facilitating migration from ethers / web3" here? Why?

**Comment by jaromil** [comment]
merged! available in latest releases, will update on apiroom in 24h
