### ISSUE TITLE
Wrong links in documentation

### ISSUE THREAD

**Issue by RebeccaSelvaggini** [dyne/Zenroom#643]
Looking at the "Zencode Advanced" section in the [documentation](https://dev.zenroom.org/), there are multiple section with wrong links in the "The script used to create the material in this page" subsection. 
These links should refer to the tests that generate the examples on the page, but actually redirect to non existing pages on GitHub.
In particular you can find these errors at:
- [Scenario credential](https://dev.zenroom.org/#/pages/zencode-scenario-credentials?id=the-script-used-to-create-the-material-in-this-page)
- [Scenario ecdh](https://dev.zenroom.org/#/pages/zencode-scenarios-ecdh?id=the-script-used-to-create-the-material-in-this-page)
- [Scenario eddsa](https://dev.zenroom.org/#/pages/zencode-scenarios-eddsa?id=the-script-used-to-create-the-material-in-this-page)
- [Scenario dp3t](https://dev.zenroom.org/#/pages/zencode-scenario-dp3t?id=the-script-used-to-create-the-material-in-this-page)
- [Scenario http](https://dev.zenroom.org/#/pages/zencode-scenarios-http?id=the-script-used-to-create-the-material-in-this-page)
- [Scenario schnorr](https://dev.zenroom.org/#/pages/zencode-scenarios-schnorr?id=the-script-used-to-create-the-material-in-this-page)
- [Scenario qp](https://dev.zenroom.org/#/pages/zencode-scenarios-qp?id=the-script-used-to-create-the-material-in-this-page)
- [Scenario bitcoin](https://dev.zenroom.org/#/pages/zencode-scenarios-bitcoin?id=the-script-used-to-create-the-material-in-this-page)
- [Scenario ethereum](https://dev.zenroom.org/#/pages/zencode-scenarios-ethereum?id=the-script-used-to-create-the-material-in-this-page)

**Comment by jaromil** [comment]
Seems they are due to the reorganization of tests in v2, most of them are fixed by adding subdir `test/zencode/...`

**Comment by Sakrecoer** [comment]
Thanks for assigning me! Will propose a PR asap! :fire:

**Comment by Sakrecoer** [comment]
@jaromil looking into this and i'm struggling to locate the repo for the docs. Any pointers would be welcome!

**Comment by matteo-cristino** [comment]
fixed in #678
