### ISSUE TITLE
Recover ethereum address from signature

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#675]
Using this code:
https://github.com/dyne/Zenroom/blob/master/src/lua/crypto_ethereum.lua#L279

we need a statement like: 

Zencode:

```
Given I have a 'ethereum signature' named 'myString.ethereum-signature' 
When I create the ethereum address from of 'myString.ethereum-signature'
Then print the 'ethereum address'

```

Data:

```
{
   "myString.ethereum-signature": "0xed8f36c71989f8660e8f5d4adbfd8f1c0288cca90d3a5330b7bf735d71ab52fe7ba0a7827dc4ba707431f1c10babd389f658f8e208b89390a9be3c097579a2ff1b"
}

```
Output:

```
{
	"ethereum_address": "0x2B8070975AF995Ef7eb949AE28ee7706B9039504"
}
```

**Comment by matteo-cristino** [comment]
First implementation done in the [feat/erecover](https://github.com/dyne/Zenroom/tree/feat/erecover) branch, the implemented statement is a draft (just for testing it) and it is
```gherkin
When I create the ethereum address from the ethereum signature 'sign' of 'message'
```
since it requires also the original message. Maybe it can be improved.

**Comment by jaromil** [comment]
Should we open a draft PR to integrate this statement?
