### ISSUE TITLE
xxd (part of vim package) required to build, not present by default in some distros - hard to debug

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#677]
Trying to build Zenroom on https://nixos.org/  
The build failed after a while. I noticed that - way before stopping - the output of make complained that "xxd is missing": it's included in the vim standard package, which apparently is not installed by default in nixos. The error was hard to find as the build process didn't stop when xxd wasn't found.

The make builds should do a check of the requirements, which appear to be:
cmake
zsh
vim

**Comment by jaromil** [comment]
It is confusing that xxd is standalone in some distros and part of vim in others. The binary is used at build time to include lua files into the const stack, building xxd ourselves may break some cross-compilation setups.
