### ISSUE TITLE
Keyword "use" in scenario ethereum

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#681]
# Situation

We have began to use the keyword "use" in the ethereum scenario: it is used when a previously created transaction is modfied to address a certain purpose, namely: 
- send eth/ERC20
- transfer ER721
- call a specific solidity SC (to store data, we used it for EBSI)
- call a generic solidity SC 

All the Zencode statements are found here:
https://github.com/dyne/Zenroom/blob/master/test/zencode/ethereum.bats
https://github.com/dyne/Zenroom/blob/master/src/lua/zencode_ethereum.lua

# Considerations
- the keyword "use" appears only in zencode_ethereum.lua
- the output of each statement containing "use" is a modified version of the previously created transaction
- the Zenocde statements that called specific solidity SC (e.g. the storage one), can be deprecated and the Zencode to call the generic solidity SC can be used instead 

# Possible solutions
- Keep the "use" keyword, possibly deriving syntax rules a posteriori 
- Deprecate the Zencode containing "use" and replace them with Zencode containing "create", which would require some work to align the data used internally by the Zencode statements

**Comment by jaromil** [comment]
Thanks for opening this issue! Let's discuss this in a meeting seeking possibilities to align the ethereum scenario as much as possible to a generic semantic. The `use` verb seems to always be auxiliary to `store` and there is perhaps an opportunity for simplification.

On a side note also a statement like:
```
When I create the string from the ethereum bytes named 'data'
```
seems it should be deprecated in favor of using an `ethereum bytes` schema.

**Comment by jaromil** [comment]
We are de-facto keeping the `use` verb, present in a number of recent cases already. Closing for now.
