### ISSUE TITLE
Foreach complexity does not seems linear

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#706]
Running the benchmark test for [ethereum signature batch verificaiton](https://github.com/dyne/Zenroom/tree/chore/eth_bench/test/benchmark/eth) uploaded in the branch [chore/eth_bench](/dyne/Zenroom/tree/chore/eth_bench) the following data are obtained:

| number of signatures | time to generate (µs) | time to verify (µs) |
|-|-|-|
|100| 231258 | 170409 |
|500| 2316432 | 1970884 |
|1000| 8113977 | 6740669 |
|5000| 181874523 | 164420876 |
|10000| 751664659 | 692456004 |

(from 1000 to 10000 there is around a x100 time increase)

plotting them the result is
* generating
![image](https://github.com/dyne/Zenroom/assets/102997993/b19f715d-691d-4ac1-b2e7-a25fe65d3daf)
* verifying
![image](https://github.com/dyne/Zenroom/assets/102997993/5a9a5c5f-50b3-4a04-82fc-7c0d4b0e2fa6)

To reproduce:
* `git checkout chore/eth_banch`
* `make linux` (avoid watchdog otherwise this will add more complexity at each step by checking the heap and almost double the time of execution)
* `cp src/zenroom /usr/local/bin`
* `cd test/benchmark/eth && ./benchmark_sign.sh <number of signatures>`

Some thoughts: 
* In the verification part a nested foreach is performed, but since they are parallel this should not increase that much the time of execution.
* One thing that I have found is that `#` (length operator) is not constant (O(1)) in lua, however it is logarithmic in the size of the list thus this should not be the real problem here (however this should be modified, computed one time and maybe stored in the iter variable).

**Comment by jaromil** [comment]
Workaround for accelerated batch operations on ethereum merged in #708 

Default iteration limit in foreach set to 1000
