### ISSUE TITLE
CBOR decoding and encoding

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#730]
Use https://github.com/Zash/lua-cbor to add the possibility to decode and encode data from and to CBOR.

As this may result difficult when covering any situation where JSON is already used, the real goals should be to:
1. be compatible with mainstream CBOR validators and interoperable with mainstream implementations (test vectors needed)
2. aim at supporting CBOR encoding for specific usage scenarios to cover standards needed in implementations (therefore no need to support all encodings for any `zenroom.*` type but just those needed in real use)

**Comment by puria** [comment]
@jaromil 🥳

**Comment by jaromil** [comment]
There is no usable C/Lua library found so far that passes validation and is easy to customise with zenroom.* types. This may be too much to fit into Zenroom, while JSON is enough of a minimal viable input/output format, so CBOR is left as a conversion to the application host.
