### ISSUE TITLE
Rule caller slangroom

### ISSUE THREAD

**Issue by albertolerda** [dyne/Zenroom#735]
Ignored statement should be at the beginning or at the end of the script.
If we encounter an unknown statement in the middle of the script we should make zenroom fail.

**Comment by matteo-cristino** [comment]
Only part left is:
* When using `logfmt = "json"` zenroom should also return a base64 encoded array called IGNORED which contains the line number of the ignored lines.

I don't think this constitute a breaking change so it can also be add later as a feature maybe. This will require a new table in ZEN memory to keep track of each linenum and then it should be encoded and print on error (or also on success?)
