### ISSUE TITLE
length keyword deprecation

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#742]
The following statement has been depreated
```gherkin
When I reate the length of ''
```
in favor of 
```gherkin
When I reate the size of ''
```
But at the same time the following statements are not deprecated
```gherkin
When I verify the length of '' is less than ''
When I verify the length of '' is less or equal than ''
When I verify the length of '' is more than ''
When I verify the length of '' is more or equal than ''
````
Do we want to deprecate also in this case the word ```length``` in favor or ```size``` (to be implemented)?

**Comment by jaromil** [comment]
I believe the size can be compared as a number, so combining two statements (creation if size and comparison of numbers) is a good replacement. Then we can deprecate these other length statements all together.

**Comment by matteo-cristino** [comment]
We created this statement in order to reduce the number of statements present in the W3C-DID server contracts. Are we sure we want to remove this statements in favor of two combined statements instead of one?
