### ISSUE TITLE
Create the JWK with secret key

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#816]
In the scenario w3c, 

We'd need to generate a JWK, from a keyring, like this

{
"jwk": {
         "alg": "ES256",
         "crv": "P-256",
         "d": "IXwHzEAHcvNNMVDGLQlODOpRO-YSecKI9_ahRaxXRdE",
         "kty": "EC",
         "x": "h-yKDTiUKmoFMpwWGkLpn6BK2SjKxwPbUQ0eTizVxLk",
         "y": "-UzD4NRmcktBNCoGRRCIXDn9F0qD342UfQyY1RtmtLA"
      }
}

with a statment similar to those: 

https://github.com/dyne/Zenroom/blob/master/src/lua/zencode_w3c.lua#L342-L354

**Comment by matteo-cristino** [comment]
Proposed statements:
```gherkin
When I create the jwk for es256
When I create the jwk for es256 with private key
```
To create respectively one without the private key (omit d) and with the private key.
This with both es256 and es256k (with all possible alias).
Moreover these statements should always start from the private key, while we can add (as already present in sd_jwt) 
```gherkin
When I create jwk for es256 of/from public key ''
```
to create a jwk from a pk.
