### ISSUE TITLE
Verify stbsp_sprintf works well on armeabi-v7a (32bit)

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#83]
This bug may or may not affect Zenroom (unverified)
https://github.com/nothings/stb/issues/871

If problems arise on named platforms, investigate further.

**Comment by powof2** [comment]
I'm guessing your test project was not built with **`android-ndk-r20b-x86_64`**?
It was fine when i built it with android-ndk-r17c-x86_64, but crash when upgraded to use **`android-ndk-r20b-x86_64`**.

**Comment by jaromil** [comment]
@powof2 We are using the ndk r19, but haven't tried yet to reproduce your problem: we have an older version of Zenroom used in production on android apps which doesn't uses stb's sprintf yet.

I will update this issue with progress and findings.

**Comment by jaromil** [comment]
We have experimented with various android builds through this year and no issues anymore.
