### ISSUE TITLE
Iterators variable after foreach loops and transition between foreach loops

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#842]
In this moment at the end of a foreach loop the iterator varibale is still present in the ACK memory, is it intended to be in this way or we should eliminate it once the foreach loop finished? Moreover there is a `Invalid transition from: endforeach` error if I try to start a new foreach after a `Endforeach`.

I saw this while I was trying to create two different foreach loop with the same iterator variable name, for example
```gherkin
Given I have a 'string array' named 'arr1'
Given I have a 'string array' named 'arr2'

When I create the 'string array' named 'res'
Foreach 'x' in 'arr1'
When I copy 'x' in 'res'
Endforeach

# add this line to overcome transition from Endforeach to Foreach
# and get error  "Cannot overwrite existing object: x"
# When done

Foreach 'x' in 'arr2'
When I copy 'x' in 'res'
Endforeach

Then print the 'res'
```
data
```json
{
	"arr1": [
		"str1",
		"str2"
	],
	"arr2": [
		"str3"
	]
}
```

**Comment by jaromil** [comment]
not intended! if we ever need memory of previous loops it should be an explicit place in heap not this one, so please go ahead and fix deleting it. Well spotted!!
