### ISSUE TITLE
Operations with time

### ISSUE THREAD

**Issue by matteo-cristino** [dyne/Zenroom#844]
Starting to work a bit more with timestamps in the `jwt` world, it turns out that we have no way to do operations with timestamps, in particular the sum that we want to use to calcuate the expiration time that should be something like `actual_timestamp+duration_of_token`. 
Note: if integer are used a string is returned instead of number, if float are used than some approximation is done and precision is lost.

Since our time variable management can change in the future (due to the upperbound set to 2147483647) I'm not sure if we want to change all operations statements to supports timestamp or create e new statement just for the sum of timestamp

**Comment by jaromil** [comment]
If this is easy then we can add support for timestamp type in all operations, as deep as overloading lua operators.

in 14 years from now when epoch touches the 8th mersenne then we'll either have a 64bit wasm target or we can change the timestamp type and have the upgrade of the base zenroom. lua type propagate everywhere.
