### ISSUE TITLE
O.from_number() does not work for "big" numbers

### ISSUE THREAD

**Issue by FilippoTrotter** [dyne/Zenroom#857]
The O.from_number() method from the file src/zen_octet.c, used to convert an integer into octets, seems to not work correctly with sufficiently large numbers. Specifically, I've noticed the issue arises with numbers larger than 2^25.The problem appears with odd numbers.
For example, the following test is passed by the function, which clearly should not happen.
```lua
assert(O.from_number(2^25-1)==O.from_number(2^25))
assert(O.from_number(2^25-3) == O.from_number(2^25-4))
````

**Comment by matteo-cristino** [comment]
This seems due to the combination of `lua_Number` as type in output of `lua_tointegerx` and the `floorf` function (Could not find any documentation of it online 🤷). 
Not totally sure why, but replacing `lua_Number` to `lua_Integer` and removing the `floorf` function make it work as intended.

**Comment by matteo-cristino** [comment]
first draft fix here [fix/oct_from_number](https://github.com/dyne/Zenroom/tree/fix/oct_from_number)
