### ISSUE TITLE
Add to Dockerfile readline-dev

### ISSUE THREAD

**Issue by Ignat99** [dyne/Zenroom#922]
# Copyright 2017-2018 Dyne.org foundation
# SPDX-FileCopyrightText: 2017-2022 Dyne.org foundation
#
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM alpine:latest

ADD . /

RUN apk add --no-cache zsh linux-headers build-base cmake **readline-dev**
RUN make linux
RUN cp /src/zenroom /usr/local/bin/zenroom

ENTRYPOINT ["zenroom"]

**Comment by matteo-cristino** [comment]
Done in #923, thank you! 😁

**Comment by Ignat99** [comment]
De nada :-)
